import React from 'react'

const Hello = () => {
  return (
    <div>
        How to make money online
Pick up freelance work online. ...
Test websites and apps. ...
Pick up tasks on Amazon's Mechanical Turk. ...
Take surveys for money. ...
5. Make money from your blog as an affiliate. ...
Sell your wares on Etsy. ...
Get advertising revenue from your blog or YouTube channel. ...
Become an Instagram influencer.
    </div>
  )
}


export default Hello
